language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
branches:
  only:
    - master
# Leaving all API browser testing commented out as there are some very node dependencies that
# need to be worked out and updated
# node_js:
#   - "0.10"
# before_install:
#   - nvm install 0.10
#   - node --version
#   - cd lib/api_browser
#   - npm install
#   - cd ../..
# script:
#   - bundle exec rspec spec
#   - cd lib/api_browser
#   - npm test
#   - cd ../..
